const initialState = {
  sales: [
    {
      id: 'office-chair-collection',
      name: 'office-chair-collection',
      price: 200,
    },
  ],
  feedbacks: [
    {
      id: '1',
      name: 'Amelia Cock',
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet est rutrum, vestibulum nisl nec, vehicula ex. Fusce vel aliquet dui, vitae venenatis erat. Sed condimentum imperdiet vestibulum. Pellentesque et venenatis tellus. Vivamus.',
      client: 'Furniture client',
      image: '/images/feedbacks/1.jpg',
    },
    {
      id: '2',
      name: 'Krystian Cyc',
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac rhoncus tortor. Integer tempus sem vitae nisi scelerisque, ut pharetra nibh pharetra. Nulla at velit augue. Integer quis tortor lectus. Duis vulputate faucibus ultricies.',
      client: 'Furniture client',
      image: '/images/feedbacks/2.jpg',
    },
    {
      id: '3',
      name: 'Emma Whine',
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mattis velit ut gravida lacinia. Duis tincidunt neque a turpis commodo, quis tristique purus vulputate. Quisque arcu sapien, volutpat ac augue vitae, finibus scelerisque purus.',
      client: 'Furniture client',
      image: '/images/feedbacks/3.jpg',
    },
    {
      id: '4',
      name: 'Grażka Dekiel',
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lobortis, neque eu consectetur ultrices, augue ante luctus purus, a aliquet mi felis nec quam. Sed sagittis accumsan orci non molestie. Aliquam tortor nisi, viverra.',
      client: 'Furniture client',
      image: '/images/feedbacks/4.jpg',
    },
  ],

  hotDeals: [
    {
      id: 'promote-1',
      name: 'promote-1',
      image: './images/hotdeals/2.jpg',
      title: 'INDOOR',
      subtitle: 'FURNITURE',
      description: 'SAVE UP TO 50% OF ALL FURNITURE',
    },
    {
      id: 'promote-2',
      name: 'promote-2',
      image: './images/hotdeals/1.jpg',
      title: 'KITCHEN',
      subtitle: 'FURNITURE',
      description: 'SAVE UP TO 40% OF ALL FURNITURE',
    },
    {
      id: 'promote-3',
      name: 'promote-3',
      image: './images/hotdeals/3.jpg',
      title: 'GARDEN',
      subtitle: 'FURNITURE',
      description: 'SAVE UP TO 60% OF ALL FURNITURE',
    },
  ],

  categories: [
    { id: 'dining', name: 'Dining', title: 'Furniture' },
    { id: 'chair', name: 'Chair', title: 'Chair' },
    { id: 'table', name: 'Table', title: 'Table' },
    { id: 'sofa', name: 'Sofa', title: 'Sofa' },
    { id: 'bed', name: 'Bed', title: 'Bedroom' },
  ],
  specialActions: [
    { id: 'featured', name: 'Featured' },
    { id: 'topSeller', name: 'Top Seller' },
    { id: 'saleOff', name: 'Sale Off' },
    { id: 'topRated', name: 'Top Rated' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      comparison: false,
      image: '/images/furnitures/1.jpg',
      myRating: 1,
      quantity: 0,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/2.jpg',
      myRating: 2,
      quantity: 0,
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      comparison: false,
      image: '/images/furnitures/3.jpg',
      myRating: 0,
      quantity: 0,
      specialAction: 'saleOff',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'chair',
      price: 20,
      salePrice: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/27.webp',
      myRating: 0,
      quantity: 0,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'chair',
      price: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/25.png',
      myRating: 5,
      quantity: 0,
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/26.png',
      myRating: 3,
      quantity: 0,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      salePrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/7.jpg',
      myRating: 0,
      quantity: 0,
      specialAction: 'saleOff',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 20,
      salePrice: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/8.jpg',
      myRating: 4,
      quantity: 0,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/9.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/10.jpg',
      specialAction: 'saleOff',
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/11.jpg',
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/12.jpg',
      specialAction: 'saleOff',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      salePrice: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/13.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparisom: true,
      image: '/images/furnitures/14.jpg',
      specialAction: 'saleOff',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/15.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      salePrice: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/16.jpg',
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      image: '/images/furnitures/17.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 45,
      salePrice: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/18.jpg',
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 15,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/19.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/20.jpg',
      specialAction: 'topSeller',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      salePrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/21.jpg',
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 15,
      salePrice: 10,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/22.jpg',
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/23.jpg',
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,

      image: '/images/furnitures/24.jpg',
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/table/table1.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/table/table2.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/table/table3.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/table/table4.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 29',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/sofa/sofa1.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 30',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/sofa/sofa2.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/sofa/sofa3.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/sofa/sofa4.jpg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/dining/dining1.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/dining/dining2.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/chair/chair1.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/chair/chair2.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/chair/chair3.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/chair/chair4.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'topRated',
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: '/images/furnitures/chair/chair5.jpeg',
      myRating: 0,
      quantity: 0,
      favorite: false,
      comparison: false,
      specialAction: 'featured',
    },
  ],
  cart: {
    products: [],
  },
  brands: [
    {
      id: 1,
      image: '/images/brands/brand-1.png',
    },
    {
      id: 2,
      image: '/images/brands/brand-2.png',
    },
    {
      id: 3,
      image: '/images/brands/brand-3.png',
    },
    {
      id: 4,
      image: '/images/brands/brand-4.png',
    },
    {
      id: 5,
      image: '/images/brands/brand-5.png',
    },
    {
      id: 6,
      image: '/images/brands/brand-6.png',
    },
    {
      id: 7,
      image: '/images/brands/brand-3.png',
    },
    {
      id: 8,
      image: '/images/brands/brand-4.png',
    },
    {
      id: 9,
      image: '/images/brands/brand-1.png',
    },
    {
      id: 10,
      image: '/images/brands/brand-5.png',
    },
    {
      id: 11,
      image: '/images/brands/brand-6.png',
    },
    {
      id: 12,
      image: '/images/brands/brand-3.png',
    },
  ],
  searchString: '',
  searchCategory: '',
  lastSearch: [],
};

export default initialState;
